name: rsync local
version: 1.7.1-migrate
slug: rsync-local
description: ðŸš¨ Addons are moved to https://github.com/Poeschl-HomeAssistant-Addons/repository
url: https://github.com/Poeschl/Hassio-Addons/tree/main/rsync-local
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant: 0.115.0
boot: manual
init: false
image: ghcr.io/poeschl-homeassistant-addons/rsync-local-{arch}
ports: {}
ports_description: {}
map:
  - share:rw
  - config:rw
  - backup:rw
  - addons:rw
  - ssl:rw
  - media:rw
devices:
  - /dev/sda1
  - /dev/sda2
  - /dev/sda3
  - /dev/sda4
  - /dev/sda5
  - /dev/sdb1
  - /dev/sdb2
  - /dev/sdb3
  - /dev/sdb4
  - /dev/sdb5
  - /dev/sdc1
  - /dev/sdc2
  - /dev/sdc3
  - /dev/sdc4
  - /dev/sdc5
  - /dev/sdd1
  - /dev/sdd2
  - /dev/sdd3
  - /dev/sdd4
  - /dev/sdd5
  - /dev/sde1
  - /dev/sde2
  - /dev/sde3
  - /dev/sde4
  - /dev/sde5
privileged:
  - SYS_ADMIN
apparmor: false
schema:
  folders:
    - source: str
      options: str?
  external_folder: match(^[^/].+)
  external_device: match(^(/dev/sd[a|b|c|d|e][1|2|3|4|5])?)
options:
  folders:
    - source: /config
  external_folder: backup
  external_device: ""
homeassistant_api: true
