name: Mopidy
version: 2.2.1-migrate
slug: mopidy
panel_icon: mdi:music-circle
description: ðŸš¨ Addons are moved to https://github.com/Poeschl-HomeAssistant-Addons/repository
url: https://github.com/Poeschl/Hassio-Addons/tree/main/mopidy
webui: http://[HOST]:[PORT:6680]/iris
arch:
  - armv7
  - armhf
  - amd64
  - i386
homeassistant: 0.115.0
startup: system
image: ghcr.io/poeschl-homeassistant-addons/mopidy-{arch}
init: false
audio: true
devices:
  - /dev/snd
map:
  - share:rw
  - media:rw
ports:
  6680/tcp: 6680
  6600/tcp: 6600
ports_description:
  6680/tcp: Web Frontend
  6600/tcp: MDP Connection
options:
  media_folder: /media/mopidy/media
  playlist_folder: /media/mopidy/playlists
  locale: en_US
  country: en
  radio_net:
    language: net
    favorite_radiostations:
      - radiobob
schema:
  media_folder: match(/share/.+|/media/.+|(smb|nfs)://.+)
  playlist_folder: match(/share/.+|/media/.+|(smb|nfs)://.+)
  custom_config: match(/share/mopidy/.+)?
  locale: match([a-z]{2}_[A-Z{2}])
  country: match([a-z]{2})
  radio_net:
    language: list(net|at|de|dk|es|fr|it|pl|pt|se)
    favorite_radiostations:
      - str
homeassistant_api: true
