language: minimal

sudo: required

branches:
  only:
  - master

git:
  depth: false

services:
  - docker

env:
  - ADDON="ICantBelieveItsNotValetudo"
  - ADDON="MaryTTS"
  - ADDON="picoTTS"

before_install:
  - sudo apt-get install jq
  - chmod +x .scripts/build.sh

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - ./.scripts/build.sh $ADDON 
