language: minimal

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - jq

env:
  - ADDON="ICantBelieveItsNotValetudo"
  - ADDON="MaryTTS"
  - ADDON="picoTTS"
  - ADDON="mopidy"

install:
  - export PATH="${HOME}/bin:${PATH}"
  - chmod +x .scripts/build.sh
  - curl -L -o hadolint "https://github.com/hadolint/hadolint/releases/download/v1.16.0/hadolint-$(uname -s)-$(uname -m)" && chmod 755 hadolint && mv hadolint ${HOME}/bin/ && hadolint --version
  - curl -L "https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.$(uname -m).tar.xz" | tar -xJv && mv "shellcheck-stable/shellcheck" ${HOME}/bin/ && shellcheck --version

before_script:
  - docker_violations=$(hadolint $ADDON/Dockerfile | tee /dev/stderr | wc -l)
  - if [ $docker_violations -gt 0 ]; then exit 2; fi
  - shellcheck $ADDON/*.sh

script:
  - ./.scripts/build.sh $ADDON 
  - ./.scripts/release.sh $ADDON 
