os: linux
language: shell

services:
  - docker

addons:
  apt:
    packages:
    - jq

env:
  - ADDON="ICantBelieveItsNotValetudo"
  - ADDON="MaryTTS"
  - ADDON="picoTTS"
  - ADDON="pigpio"
  - ADDON="mpd"
  - ADDON="valetudo-mapper"
  - ADDON="ympd"
  - ADDON="git-exporter"
  - ADDON="syncthing"
  - ADDON="OWASP-ZAP"

install:
  - export PATH="${HOME}/bin:${PATH}"
  - export FORCE_PUSH=false
  - chmod +x .scripts/build.sh
  - curl -L -o hadolint "https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-$(uname -s)-$(uname -m)" && chmod 755 hadolint && mv hadolint ${HOME}/bin/ && hadolint --version
  - curl -L "https://storage.googleapis.com/shellcheck/shellcheck-v0.7.0.linux.$(uname -m).tar.xz" | tar -xJv && mv "shellcheck-v0.7.0/shellcheck" ${HOME}/bin/ && shellcheck --version

before_script:
  - docker_violations=$(hadolint $ADDON/Dockerfile | tee /dev/stderr | wc -l)
  - if [ $docker_violations -gt 0 ]; then exit 2; fi
  - shellcheck $ADDON/*.sh

script:
  - ./.scripts/build.sh $ADDON 
  - ./.scripts/release.sh $ADDON 
