name: Pixelflut
version: 1.2.2-migrate
slug: pixelflut
panel_icon: mdi:waves
description: ðŸš¨ Addons are moved to https://github.com/Poeschl-HomeAssistant-Addons/repository
url: https://github.com/Poeschl/Hassio-Addons/tree/main/pixelflut
ingress: true
ingress_port: 6080
ingress_entry: vnc.html?autoconnect=true
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
image: ghcr.io/poeschl-homeassistant-addons/pixelflut-{arch}
init: false
ports:
  1234/tcp: 1234
  1235/tcp: null
  5900/tcp: null
ports_description:
  1234/tcp: The Pixelflut port to send your requests
  1235/tcp: Provides json statistics about the running canvas
  5900/tcp: VNC access of the Pixelflut canvas
options:
  width: "1280"
  height: "720"
  description: Pixelflut
schema:
  width: int(0,)
  height: int(0,)
  description: str
homeassistant_api: true
