name: rsync
version: 1.7.1-migrate
slug: rsync
description: ðŸš¨ Addons are moved to https://github.com/Poeschl-HomeAssistant-Addons/repository
url: https://github.com/Poeschl/Hassio-Addons/tree/main/rsync
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant: 0.115.0
boot: manual
init: false
image: ghcr.io/poeschl-homeassistant-addons/rsync-{arch}
ports: {}
ports_description: {}
map:
  - share:rw
  - config:rw
  - backup:rw
  - addons:rw
  - ssl:rw
  - media:rw
schema:
  private_key_file: match(^/ssl/.+)
  username: str
  folders:
    - source: str
      destination: str
      options: str?
  remote_host: str
  remote_port: port?
options:
  private_key_file: /ssl/rsync/id_rsa
  username: user
  folders:
    - source: /config
      destination: /home/user
  remote_host: ""
homeassistant_api: true
