name: ICantBelieveItsNotValetudo
version: 4.1.0-migrate
slug: icantbelieveitsnotvaletudo
description: ðŸš¨ Addons are moved to https://github.com/Poeschl-HomeAssistant-Addons/repository
url: https://github.com/Poeschl/Hassio-Addons/tree/main/ICantBelieveItsNotValetudo
arch:
  - armv7
  - aarch64
  - amd64
  - i386
image: ghcr.io/poeschl-homeassistant-addons/icantbelieveitsnotvaletudo-{arch}
ports:
  8080/tcp:
ports_description:
  8080/tcp: Port serving the floor plan (Not required for Supervisor Ingress)
ingress: true
ingress_port: 8080
panel_title: Valetudo Floorplan
panel_icon: mdi:floor-plan
init: false
map:
  - ssl
schema:
  mapSettings:
    drawPath: bool
    drawCharger: bool
    drawRobot: bool
    scale: int(0,)
    rotate: int(0,)
    crop_top: int(0,)?
    crop_bottom: int(0,)?
    crop_left: int(0,)?
    crop_right: int(0,)?
    padding_top: int(0,)?
    padding_bottom: int(0,)?
    padding_right: int(0,)?
    padding_left: int(0,)?
  mapColors:
    floor: match(#(?:[0-9a-fA-F]{2}){2,4}$|(#[0-9a-fA-F]{3})$)
    obstacle: match(#(?:[0-9a-fA-F]{2}){2,4}$|(#[0-9a-fA-F]{3})$)
    path: match(#(?:[0-9a-fA-F]{2}){2,4}$|(#[0-9a-fA-F]{3})$)
    segments: match(#(?:[0-9a-fA-F]{2}){2,4}$|(#[0-9a-fA-F]{3})$)?
  mqtt:
    identifier: str
    topicPrefix: str
    autoconfPrefix: str
    broker_url: match(^mqtts?://(.+:.+@)?[^:@]+(:[0-9]+)?$)
    caPath: str
    mapDataTopic: str
    minMillisecondsBetweenMapUpdates: int
    publishMapImage: bool
options:
  mapSettings:
    drawPath: true
    drawCharger: true
    drawRobot: true
    scale: 4
    rotate: 0
  mapColors:
    floor: "#0076ff"
    obstacle: "#52aeff"
    path: "#ffffff"
  mqtt:
    identifier: rockrobo
    topicPrefix: valetudo
    autoconfPrefix: homeassistant
    broker_url: mqtt://user:pass@foobar.example
    caPath: ""
    mapDataTopic: valetudo/rockrobo/MapData/map-data
    minMillisecondsBetweenMapUpdates: 10000
    publishMapImage: true
homeassistant_api: true
