name: Check PR
on:
  pull_request:
    branches:
      - master

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_on_error: true

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          pattern: "*.sh"

  check-build:
    name: Check build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [
          "ICantBelieveItsNotValetudo",
          "MaryTTS",
          "picoTTS",
          "pigpio",
          "mpd",
          "valetudo-mapper",
          "ympd",
          "git-exporter",
          "syncthing",
          "OWASP-ZAP",
          "mitmproxy",
          "rsync"
        ]
      fail-fast: false
    steps:
      - name: Detect chanced files
        id: files-check
        uses: dorny/paths-filter@v2.4.2
        with:
          filters: |
            changed:
              - ${{matrix.addon}}/**

      - name: Checkout
        if: steps.files-check.outputs.changed == 'true'
        uses: actions/checkout@v2

      - name: Get config
        id: config
        if: steps.files-check.outputs.changed == 'true'
        shell: bash
        run: |
          IFS='/' read -r registry imagetemplate <<< "$(jq -r '.image' "${{ matrix.addon }}/config.json")"
          version=$(jq -r '.version' "${{ matrix.addon }}/config.json")
          archs=$(jq -r '.arch // ["armv7", "armhf", "amd64", "aarch64", "i386"] | [.[] | .] | join(" ")' "${{ matrix.addon }}/config.json")
          archs_param=$(jq -r '.arch // ["armv7", "armhf", "amd64", "aarch64", "i386"] | [.[] | "--" + .] | join(" ")' ${{ matrix.addon }}/config.json)

          echo "Docker Registry: $registry"
          echo "Imagetemplate: $imagetemplate"
          echo "Version: $version"
          echo "Architectures: $archs"

          echo "::set-output name=registry::$registry"        
          echo "::set-output name=imagetemplate::$imagetemplate"
          echo "::set-output name=version::$version"
          echo "::set-output name=archs_param::$archs_param"

      - name: Build addon
        if: steps.files-check.outputs.changed == 'true'
        uses: home-assistant/builder@2020.10.0
        with:
          args: >
            ${{ steps.config.outputs.archs_param }}
            -t /data/${{ matrix.addon }}
            -d ${{ steps.config.outputs.registry }}
            -i ${{ steps.config.outputs.imagetemplate }}
            --cache-tag cache
            --no-latest
            --test

      - name: Check images
        if: steps.files-check.outputs.changed == 'true'
        shell: bash
        run: |
          missing=0
          for image_name in ${{ steps.config.outputs.image_names }}; do
            if [[ "$(docker images -q "$image_name:${{ steps.config.outputs.version }}" 2> /dev/null)" == "" ]]; then
              echo "::error::No local image for $image_name found."
              missing=$((missing + 1))
            else
              echo "Image $image_name found."
            fi
          done
          if [ "$missing" -gt "0" ]; then
            docker images
            exit 1
          fi