name: Check PR Build
on:
  pull_request:
    branches:
      - master

jobs:
  check-addon-changes:
    runs-on: ubuntu-latest
    outputs:
      changedAddons: ${{ steps.filter.outputs.changes }}
      changedChangelogFiles: ${{ steps.changed-files.outputs.changelogs_files }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Detect chanced addons
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: .github/paths-filter.yml

    - name: Detect chanced files
      uses: dorny/paths-filter@v2
      id: changed-files
      with:
        list-files: csv
        filters: |
          changelogs:
            - '**/CHANGELOG.md'

  check-changed-changelog:
    name: Check if CHANGELOG.md changed
    if: ${{ needs.check-addon-changes.outputs.changedAddons != '[]' }}
    runs-on: ubuntu-latest
    needs: check-addon-changes
    strategy:
      fail-fast: false
      matrix:
        addon: ${{ fromJSON(needs.check-addon-changes.outputs.changedAddons) }}
    steps:

      - name: Check for updated CHANGELOG.md
        shell: bash
        run: |
          if [[ ! "${{ needs.check-addon-changes.outputs.changedChangelogFiles }}" =~ "${{ matrix.addon }}/CHANGELOG.md" ]]; then
              echo "::error::No new entries in ${{ matrix.addon }} CHANGELOG.md file!"
              exit 1
          fi

  check-version-matching:
    name: Check for same addon versions
    if: ${{ needs.check-addon-changes.outputs.changedAddons != '[]' }}
    runs-on: ubuntu-latest
    needs: check-addon-changes
    strategy:
      fail-fast: false
      matrix:
        addon: ${{ fromJSON(needs.check-addon-changes.outputs.changedAddons) }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if versions of CHANGELOG.md and config.json match
        shell: bash
        run: |
          config_version=$(sed -nr "s/.*version.*\"(.+)\".*/\1/p" "${{ matrix.addon }}/config.json")
          changelog_version=$(sed -nr "0,/#{1,2}\s+(\S+)\s+-.*/{s//\1/p}" "${{ matrix.addon }}/CHANGELOG.md")
          if [[ ! "$config_version" = "$changelog_version" ]]; then
              echo "::error::The config version does not match the latest Changelog version!"
              exit 1
          fi 

  check-build:
    name: Check build
    if: ${{ needs.check-addon-changes.outputs.changedAddons != '[]' }}
    runs-on: ubuntu-latest
    needs: check-addon-changes
    strategy:
      fail-fast: false
      matrix:
        addon: ${{ fromJSON(needs.check-addon-changes.outputs.changedAddons) }}
    container:
      image: homeassistant/amd64-builder:2021.03.4
      options: --rm --privileged
    env:
      DOCKER_BUILDKIT: 1
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get config
        id: config
        shell: bash
        run: |
          IFS='/' read -r registry imagetemplate <<< "$(jq -r '.image' "${{ matrix.addon }}/config.json")"
          version=$(jq -r '.version' "${{ matrix.addon }}/config.json")
          archs=$(jq -r '.arch // ["armv7", "armhf", "amd64", "aarch64", "i386"] | [.[] | .] | join(" ")' "${{ matrix.addon }}/config.json")
          archs_param=$(jq -r '.arch // ["armv7", "armhf", "amd64", "aarch64", "i386"] | [.[] | "--" + .] | join(" ")' ${{ matrix.addon }}/config.json)

          image_names=""
          if [[ "$imagetemplate" != 'null' ]]; then
            for arch in ${archs}; do
              image_names="${image_names} ${registry}/${imagetemplate/\{arch\}/$arch}"
            done
          fi

          echo "Docker Registry: $registry"
          echo "Imagetemplate: $imagetemplate"
          echo "Version: $version"
          echo "Architectures: $archs"
          echo "Images: $image_names"

          echo "::set-output name=registry::$registry"        
          echo "::set-output name=imagetemplate::$imagetemplate"
          echo "::set-output name=version::$version"
          echo "::set-output name=archs_param::$archs_param"
          echo "::set-output name=image_names::$image_names"

      - name: Remove untagged images
        shell: bash
        env:
          GHCR_TOKEN: ${{ secrets.CR_PAT }}
        run: |
          apk add --no-cache python3 py3-dateutil py3-requests
          curl https://raw.githubusercontent.com/airtower-luna/hello-ghcr/main/ghcr-prune.py -o ghcr-prune.py

          for image_name in ${{ steps.config.outputs.image_names }}; do
            python3 ghcr-prune.py --prune-age 0 --container "$image_name" --dry-run
          done

      - name: Build addon
        run: >
          /usr/bin/builder.sh
          ${{ steps.config.outputs.archs_param }}
          -t ${{ matrix.addon }}
          -d ${{ steps.config.outputs.registry }}
          -i ${{ steps.config.outputs.imagetemplate }}
          --cache-tag cache
          --no-latest
          --test

      - name: Check images
        shell: bash
        run: |
          missing=0
          for image_name in ${{ steps.config.outputs.image_names }}; do
            if [[ "$(docker images -q "$image_name:${{ steps.config.outputs.version }}" 2> /dev/null)" == "" ]]; then
              echo "::error::No local image for $image_name found."
              missing=$((missing + 1))
            else
              echo "Image $image_name found."

              entrypoint=$(docker inspect "$image_name:${{ steps.config.outputs.version }}" | jq --raw-output '.[].Config.Entrypoint[]' 2>/dev/null || echo '')
              cmd=$(docker inspect "$image_name:${{ steps.config.outputs.version }}" | jq --raw-output '.[].Config.Cmd[]' 2>/dev/null || echo '')
              if [ -n "$cmd" ] || ([ "$entrypoint" != "/init" ] && [ "$entrypoint" != "/run.sh" ]); then
                echo "::error::Invalid docker entrypoint found (Detected Entrypoint: '${entrypoint}', Detected Cmd: '${cmd}')"
                exit 1
              fi
              
            fi
          done
          if [ "$missing" -gt "0" ]; then
            docker images
            exit 1
          fi
